// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg3IXdsTCLVlKhGTSCgirIhSQGoOD2cEM',
    appId: '1:760730884726:web:38773f20c334fab0d91d57',
    messagingSenderId: '760730884726',
    projectId: 'general-tests-dc287',
    authDomain: 'general-tests-dc287.firebaseapp.com',
    storageBucket: 'general-tests-dc287.appspot.com',
    measurementId: 'G-R2C07EKC1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRL00DzthiO85itlYBT1bdJrpPCVgyuiI',
    appId: '1:760730884726:android:1db01050b4f58ba6d91d57',
    messagingSenderId: '760730884726',
    projectId: 'general-tests-dc287',
    storageBucket: 'general-tests-dc287.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ6-hGt5AHfRTbuWVH8J3RThhgJ7_F7k8',
    appId: '1:760730884726:ios:ee56616d6fbc68f9d91d57',
    messagingSenderId: '760730884726',
    projectId: 'general-tests-dc287',
    storageBucket: 'general-tests-dc287.appspot.com',
    androidClientId: '760730884726-ca9ob9i8f9g9iqs1c0r1gassf83if79r.apps.googleusercontent.com',
    iosClientId: '760730884726-nfjb9b2nlgltdv3a0de4d83fevp03ab6.apps.googleusercontent.com',
    iosBundleId: 'com.sdw.ivana.singularTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ6-hGt5AHfRTbuWVH8J3RThhgJ7_F7k8',
    appId: '1:760730884726:ios:ee56616d6fbc68f9d91d57',
    messagingSenderId: '760730884726',
    projectId: 'general-tests-dc287',
    storageBucket: 'general-tests-dc287.appspot.com',
    androidClientId: '760730884726-ca9ob9i8f9g9iqs1c0r1gassf83if79r.apps.googleusercontent.com',
    iosClientId: '760730884726-nfjb9b2nlgltdv3a0de4d83fevp03ab6.apps.googleusercontent.com',
    iosBundleId: 'com.sdw.ivana.singularTest',
  );
}
